import { StyleSheet } from "react-native";

export const stylesSignUp = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: "#F0F4F8", // Fondo suave y moderno
  },
  container: {
    flex: 1,
    padding: 20,
    width: "100%",
    maxWidth: 600,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  imageUser: {
    width: 120,
    height: 120,
    marginBottom: 20,
    resizeMode: "cover",
  },
  text: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
    textShadowColor: "#aaa",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  formLogin: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  user: {
    marginBottom: 15,
  },
  textUser: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 5,
  },
  textInputUser: {
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#333",
    backgroundColor: "#FAFAFA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  pass: {
    marginBottom: 15,
  },
  textPass: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 5,
  },
  textInputPass: {
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#333",
    backgroundColor: "#FAFAFA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    flex: 1,
  },
  roles: {
    fontSize: 16,
    fontWeight: "600",
    color: "#444",
    marginVertical: 10,
  },
  pickerContainer: {
    marginBottom: 20,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  picker: {
    width: "100%",
  },
  pickerIOS: {
    height: 150,
    width: "100%",
  },
  newAccountView: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },
  newAccountText: {
    fontSize: 14,
    color: "#555",
    marginRight: 5,
  },
  textSignin: {
    fontSize: 14,
    color: "#007BFF",
    textDecorationLine: "underline",
  },
  signInButton: {
    backgroundColor: "#6F42C1",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  signInText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  imageShowPassword: {
    width: 30,
    height: 30,
  },
  buttonShowPassword: {
    position: "absolute",
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    padding: 10,
    zIndex: 3000,
  },
});
