import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f8f8",
    padding: 20,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 20,
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
  },
  reviewTexts: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textsH2: {
    fontSize: 18,
    color: "#333",
    marginVertical: 5,
  },
  label: {
    fontSize: 16,
    color: "#555",
    marginVertical: 5,
  },
  datesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
  },
  datePickers: {
    width: "45%",
    marginBottom: 10,
  },
  dateText: {
    fontSize: 16,
    color: "#fff",
    marginTop: 10,
    marginBottom: 15,
    padding: 5,
    textAlign: "center",
  },
  buttonPickDate: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#007BFF",
    borderRadius: 5,
    alignItems: "center",
    marginBottom: 15,
  },
  buttonContainer: {
    backgroundColor: "#28a745",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  buttonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  saleItem: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  saleText: {
    fontSize: 16,
    color: "#555",
    marginBottom: 8,
  },
  bold: {
    fontWeight: "bold",
    color: "#000",
  },
  deleteOrder: {
    marginTop: 15,
    paddingVertical: 10,
    backgroundColor: "#dc3545",
    borderRadius: 5,
    alignItems: "center",
  },
  textsDelete: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  alertContainer: {
    position: "absolute",
    top: "40%",
    left: "10%",
    right: "10%",
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  alertText: {
    fontSize: 16,
    color: "#333",
    marginBottom: 10,
  },
});

export default styles;
