import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "../components/context/LayoutContext"; // Asegúrate de importar tu contexto

export const stylesSignUp = () => {
  const { isWeb, isTablet, isLargeTablet } = useResponsiveLayout();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F9F9F9",
      paddingHorizontal: 20,
    },
    scrollView: { flex: 1 },
    imageUser: {
      width: 120,
      height: 120,
      marginBottom: 20,
    },
    text: {
      fontSize: 28,
      fontWeight: "bold",
      fontFamily: "fontApp",
      color: "#333",
      textAlign: "center",
      marginBottom: 20,
      textShadowColor: "#aaa",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    formSignin: {
      width: "100%",
      padding: 20,
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 5,
      maxWidth: isWeb || isTablet || isLargeTablet ? 500 : "100%",
      minWidth: isWeb || isTablet || isLargeTablet ? 300 : "auto",
    },
    user: {
      marginBottom: 15,
    },
    textUser: {
      fontSize: 16,
      fontFamily: "fontApp",
      color: "#555",
      fontWeight: "bold",
      marginBottom: 5,
    },
    textInputUser: {
      height: 45,
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#FAFAFA",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      fontFamily: "fontApp",
      shadowRadius: 2,
      elevation: 2,
    },
    pass: {
      marginBottom: 15,
    },
    textPass: {
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "fontApp",
      color: "#555",
      marginBottom: 5,
    },
    textInputPass: {
      height: 45,
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#FAFAFA",
      fontFamily: "fontApp",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
      flex: 1,
    },
    newAccountView: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      margin: 8,
      padding: 10,
    },
    newAccountText: {
      fontSize: 16,
      color: "#555",
      marginRight: 5,
      fontFamily: "fontApp",
    },
    textLogIn: {
      fontSize: 14,
      color: "#007BFF",
      fontWeight: "bold",
      textDecorationLine: "underline",
      fontFamily: "fontApp",
    },
    signInButton: {
      height: 50,
      backgroundColor: "#6F42C1",
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
    },
    signInText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
      fontFamily: "fontApp",
    },
    imageShowPassword: {
      width: 30,
      height: 30,
    },
    videoShowPassword: {
      width: 40,
      height: 40,
      right: -5,
    },
    buttonShowPassword: {
      position: "absolute",
      right: 10,
      top: 0,
      bottom: 0,
      justifyContent: "center",
      padding: 10,
      zIndex: 3000,
    },
    main: {
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    buttonLogIn: {
      justifyContent: "center",
      alignItems: "center",
    },
    textLogin: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#007BFF",
      textDecorationLine: "underline",
      marginRight: 5,
      fontFamily: "fontApp",
    },
    roles: {
      fontSize: 16,
      fontFamily: "fontApp",
      color: "#555",
      fontWeight: "bold",
      marginBottom: 5,
    },
    pickerContainer: {},
    picker: {
      maxHeight: 60,
      borderWidth: 1,
      borderColor: "#DDD",
      backgroundColor: "#FAFAFA",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      fontFamily: "fontApp",
      shadowRadius: 2,
      elevation: 3,
    },
    pickerIOS: {
      height: 45,
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#FAFAFA",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      fontFamily: "fontApp",
      shadowRadius: 2,
      elevation: 2,
    },
  });
};
